---
name: Hide Previous Comments
description: Hide comments previously posted by action

inputs:
  GITHUB_TOKEN:
    description: GitHub Token
    required: true
  PR_NUMBER:
    description: Pull Request Number
    required: true

runs:
  using: composite
  steps:
    - name: Setup github-comment
      uses: shmokmt/actions-setup-github-comment@v2
    - id: hide-comment
      shell: bash
      run: |
        github-comment hide -org "$OWNER" -repo "$REPO" -pr "$PR_NUMBER" -condition 'Comment.Meta.SHA1 != Commit.SHA1 && (Comment.Meta.WorkflowName == "Update Pull Request With Comment")'
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        PR_NUMBER: ${{ inputs.PR_NUMBER }}
