---
name: Test Docker Images

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  registry: quay.io

  # ${{ env.registry }}

jobs:
  files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Get Git Changed File Directories
        id: directories
        uses: tj-actions/changed-files@cc733854b1f224978ef800d29e4709d5ee2883e4 # v44.5.5
        with:
          dir_names: false
          json: true
          escape_json: false
          files: |
            **/Dockerfile
      - name: Output Changed Directories
        run: echo ${{ steps.directories.outputs.all_changed_files }}
    outputs:
      dirs: ${{ steps.directories.outputs.all_changed_files }}

  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filepath-matrix.outputs.matrix }}

    steps:
      - name: Set job matrix
        id: filepath-matrix
        run: |
          echo ${{ toJson(needs.files.outputs.dirs) }} # debug
  #
  # build:
  #   runs-on: ubuntu-latest
  #   needs: prepare
  #   strategy:
  #     matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
  #
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #
  #     - name: Log in to GHCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #
  #     - name: Build and Push Docker Image
  #       run: |
  #         echo "Building and pushing image for ${{ matrix.image_name }} from ${{ matrix.path }}"
  #         docker buildx build --platform linux/amd64 --push -t "${{ matrix.image_name }}" -f "${{ matrix.path }}" "$(dirname ${{ matrix.path }})"
