---
name: Test Docker Images

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  registry: quay.io

  # ${{ env.registry }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filepath-matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find Changed Dockerfiles
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            docker:
              - '**/Dockerfile'

      - name: Set job matrix
        id: filepath-matrix
        run: |
          echo "${{ steps.filter.outputs.docker_files }}"
  #
  # build:
  #   runs-on: ubuntu-latest
  #   needs: prepare
  #   strategy:
  #     matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
  #
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #
  #     - name: Log in to GHCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #
  #     - name: Build and Push Docker Image
  #       run: |
  #         echo "Building and pushing image for ${{ matrix.image_name }} from ${{ matrix.path }}"
  #         docker buildx build --platform linux/amd64 --push -t "${{ matrix.image_name }}" -f "${{ matrix.path }}" "$(dirname ${{ matrix.path }})"
